spring.application.name=olimpiadas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# =========================
# BASE DE DATOS LOCAL
# =========================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/olimpiadas_peru}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================
# CONFIGURACION DE VARIABLES DE ENTORNO PARA DESPLIEGUE
# Recomendado para produccion o despliegue.
# DB_URL=jdbc:postgresql://servidor:5432/olimpiadas_peru
# DB_USERNAME=usuario_seguro
# DB_PASSWORD=contrasena_segura
# JWT_SECRET=clave-secreta-de-al-menos-32-caracteres
# spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
server.servlet.context-path=/olimpiadas

jwt.secret=${JWT_SECRET:clave-super-secreta-para-jwt-cambiar-en-produccion-2026}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:5500,http://localhost:8080,http://127.0.0.1:8080}
## configuracion para el envio de correo con gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username={username}
spring.mail.password={mail-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.reset-password-url=http://127.0.0.1:5500/frontend/recuperar-password.html
app.password-reset.expiration-minutes=30
