spring.application.name=olimpiadas

# =========================
# BASE DE DATOS LOCAL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/olimpaidas_peru
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================
# CONFIGURACION DE VARIABLES DE ENTORNO PARA DESPLIEGUE
# Recomendado para produccion o despliegue.
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
server.servlet.context-path=/votacion

jwt.secret=clave-super-secreta-para-jwt-cambiar-en-produccion-2026
jwt.expiration=900000
jwt.refresh-expiration=604800000

app.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:5500,http://localhost:8080,http://127.0.0.1:8080,null
## configuracion para el envio de correo con gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username={username}
spring.mail.password={mail-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.reset-password-url=http://127.0.0.1:5500/frontend/recuperar-password.html
app.password-reset.expiration-minutes=30
